name: Hello World

on:
    workflow_dispatch:

jobs:
    first-workflow:
        runs-on: ubuntu-latest
        steps:
            - run: echo " Hello from an inline Bash script in a GitHub Action workFlow"
